services:
  postgres:
    container_name: caloree-postgres
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD

  server:
    container_name: caloree-server
    image: stefanostouf/caloree-server:0.1.0-SNAPSHOT
    environment:
      - CALOREE_DEFAULT_USERNAME
      - CALOREE_DEFAULT_PASSWORD
      - POSTGRES_PASSWORD
    ports:
      - 8080:8080

volumes:
  db_data:
    external: true
    name: db_data