services:
  postgres:
    container_name: caloree-postgres
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432

  server:
    container_name: caloree-server
    image: stefanostouf/caloree-server:0.1.0-SNAPSHOT
    environment:
      - DEFAULT_USERNAME
      - DEFAULT_PASSWORD

volumes:
  db_data:
    external: true
    name: db_data