services:
  caloree-postgres:
    container_name: caloree-postgres
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - "./scripts/init-caloree-user.sh:/docker-entrypoint-initdb.d/init-caloree-user.sh"
    environment:
      - POSTGRES_PASSWORD
      - CALOREE_USER_PASSWORD
    ports:
      - 5432:5432

  caloree-server:
    depends_on:
      - caloree-postgres
    container_name: caloree-server
    image: stefanostouf/caloree-server:0.1.0-SNAPSHOT
    environment:
      - CALOREE_DEFAULT_USERNAME
      - CALOREE_DEFAULT_PASSWORD
      - CALOREE_USER_PASSWORD
    ports:
      - 8080:8080

volumes:
  db_data:
    external: true
    name: db_data
