version: "3.3"

services:
  caloree-postgres:
    container_name: caloree-postgres
    image: stefanostouf/caloree-postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - CALOREE_USER_PASSWORD
    ports:
      - "5432:5432"

  caloree-server:
    depends_on:
      - caloree-postgres
    container_name: caloree-server
    image: stefanostouf/caloree-server:0.1.0
    environment:
      - CALOREE_DEFAULT_USERNAME
      - CALOREE_DEFAULT_PASSWORD
      - CALOREE_USER_PASSWORD
    ports:
      - "8080:8080"

volumes:
  db_data:
    external: true
