services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432

volumes:
  db_data:
    external: true
    name: db_data