name: actions

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run test and upload container
        uses: matankdr/github-docker-sbt@11.0.5-1.3.8-DOCKER-IVY-CREDS7
        with:
          command: docker:publish
          packages-resolver: "ivy creds"
          docker-login-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-login-password: ${{ secrets.DOCKERHUB_PASSWORD }}